name: Continuous Integration

on:
  push:
    branches:
      - Ecommerce_Company_Arc

  pull_request:
    branches:
      - Ecommerce_Company_Arc

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Python Installation
        run: |
          python --version

      - name: Verify Pip
        run: |
          pip --version

      - name: Verify Installed Packages
        run: |
          pip list